apiVersion: v2
name: outline
description: A Helm chart for https://github.com/outline/outline
type: application
version: 0.2.0
appVersion: 0.63.0
dependencies:
  - name: redis
    version: ~12.8.3
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Gabriel Monta√±ola
    email: gabriel.ricardo@iclinic.com.br
  - name: Marcio Rodrigues
    email: marcio.godoy@iclinic.com.br
sources:
  - https://github.com/iclinic/charts
