apiVersion: v2
name: outline
description: A Helm chart for https://github.com/outline/outline
type: application
version: 0.1.0
appVersion: 0.53.0
dependencies:
  - name: redis
    version: ~12.8.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
maintainers:
  - name: Gabriel Monta√±ola
    email: gabriel.ricardo@iclinic.com.br
  - name: Marcio Rodrigues
    email: marcio.godoy@iclinic.com.br
sources:
  - https://github.com/iclinic/outline-helm